patterns = [ [{'TEXT':'KPMG'}],
             [{'TEXT':'PricewaterhouseCoopers'}],
             [{'TEXT':'Ernst'},{'IS_PUNCT':True},{'TEXT':'Young'}],
             [{'TEXT':'EY'}],
             [{'TEXT':'Deloitte'}],
             [{'TEXT':'PwC'}]
           ]

NAME_TEXT = ["for and on behalf of KPMG LLP, Statutory Auditor",
             "for and on behalf of PricewaterhouseCoopers LLP",
             "for and on behalf of Ernst & Young LLP, Statutory Auditor",
             "for and on behalf of Deloitte LLP",
             "For and on behalf of Deloitte Ireland LLP",
             "KPMG audit partner",
             "The following fees were paid or are payable to the company’s auditors, KPMG LLP and other firms in the KPMG network",
             "Following an external audit tender in 2015, KPMG was appointed as Barclays’ Statutory Auditor",
             "KPMG was appointed by shareholders as the Group’s Statutory Auditor in 2016 following a formal tender process.",
             "KPMG LLP (KPMG) has been the company’s External Auditor since",

             "Confirmed the external auditor, PwC, remains independent",
             "The external auditors are PwC who were first appointed for the financial year commencing 1 January 2016 following a competitive tender process.",
             "External Auditors PricewaterhouseCoopers LLP",
             "the relationship with the Group’s current audit firm KPMG LLP (KPMG)",
             "The Group’s external auditor is KPMG LLP (KPMG)",
             "PricewaterhouseCoopers LLP (PwC) was appointed as the Group’s external auditor ",
             "Given the continuing effectiveness of PwC in their role as external auditor",
             " it is in the best interests of shareholders for PwC to remain as external auditor for the following financial year",
             "The Committee therefore recommended to the Board that a resolution to reappoint PwC as external auditor of the Company",
             "Deloitte LLP (Deloitte) continues as the Group’s external auditor. ",

             "PwC were appointed as the Group’s external auditor for the financial year ",
             "KPMG has been the Group’s auditor since 2018",
             "the external auditor, PricewaterhouseCoopers LLP,"
             "The current external auditor, PricewaterhouseCoopers LLP, was appointed in 2007.",
             "The Board appointed PricewaterhouseCoopers LLP (PwC) as external auditor in June 2014",
             "During the period, PricewaterhouseCoopers LLP, the Group’s auditor, provided the following services",
             "As regards external audits, the sustainability performance accounted in the Report is subject to limited audit by an independent firm (PricewaterhouseCoopers",
             "The legal audit of the accounts is entrusted to PricewaterhouseCoopers S.p.A., an external auditing firm included in the register of accounting auditors. ",
             "The  firm  appointed  to  undertake  the  external  audit  of  the  accounts  of  the  Company  is PricewaterhouseCoopers S.p.A. (the “ExternalAuditing Firm”),",
             "The Audit Committee has now overseen the first year following a transition in the External Auditor, working with Ernst and Young LLP. ",

             "This statement is subject to review by Deloitte, our external auditor.",
             "The lead audit engagement partners for EY in Australia and the United Kingdom (together, ‘EY’) were appointed for commencement from 1 July 2019",
             "the Board announced it had selected EY to be the Group’s auditor from the financial year",
             "EY was the auditor during FY2020.",
             "The 2020 financial year-end is KPMG LLP’s third financial reporting period as the Group’s external auditor,",
             "During the year, Deloitte provided external audit services for regulatory and statutory reporting. ",
             "The performance of the Company’s external auditor, KPMG LLP, is kept under review by the Board and the Committee.",
             "KPMG was appointed as external auditor in July 2015",
             "Deloitte LLP Statutory Audit",
             "Deloitte LLP was originally appointed by the shareholders in 2018 as our external auditor",

             "The  Company  engaged Deloitte & Touche  LLP,  an  independent  registered  public accounting f irm, to audit  and  render  an opinion  on  the  consolidated  f inancial  statements",
             "Deloitte was appointed as auditor of the company",
             "the Committee has recommended to the Board that Deloitte be reappointed under the current external audit contract ",
             "Deloitte’s audit of the Group financial statements for the year ended",
             "shareholders approved the appointment of PricewaterhouseCoopers LLP (PwC) as the Company’s new Statutory Auditor.",
             "to propose to shareholders the re-appointment of PwC as auditor ",
             "in its capacity as Group external auditor, PwC undertakes an audit of the relevant sections",
             "with its external auditors, PricewaterhouseCoopers LLP (PwC), ",
             "A resolution will be proposed at the AGM on 30 April 2021 for the reappointment of PricewaterhouseCoopers LLP (PwC) as auditor of the Company. ",
             "during 2020, PwC undertook various audit and audit related services.",
             ]
